export const DONATION_CREATED = 'DONATION_CREATED';
export const APPOINTMENT_CREATED = 'APPOINTMENT_CREATED';
export const INQUIRY_CREATED = 'INQUIRY_CREATED';
export const APPLICATION_CREATED = 'APPLICATION_CREATED';
export const SERVICE_REQUEST_CREATED = 'SERVICE_REQUEST_CREATED';
export const REGISTRATION_CREATED = 'REGISTRATION_CREATED';

export const NOTIFICATION_EVENTS = [
  DONATION_CREATED,
  APPOINTMENT_CREATED,
  INQUIRY_CREATED,
  APPLICATION_CREATED,
  SERVICE_REQUEST_CREATED,
  REGISTRATION_CREATED,
] as const;

export type NotificationEvent = (typeof NOTIFICATION_EVENTS)[number];
